### ISSUE TITLE
Tracking issue for next release

### ISSUE THREAD

**Issue by newAM** [newAM/w5500-rs#92]
There are some big changes upcoming, including an API for streaming bytes from the socket buffers (finally!).

This is a TODO list of things I want to do before the next set of releases.

* [x] Release regsim first since those are small changes
* [x] Run the HL testsuite with physical hardware
* [x] Run `cargo-spellcheck` on the docs
* [x] Read the HL and DHCP documentation for added / changed functions
* [ ] Add test coverage for TCP readers & writers, either by implementing MQTT with tests, or direct testing.
* [x] Fix the hostname TODO in DHCP land, move DNS `Hostname` to HL?
* [x] `rg todo`
* [ ] Check that handling for DNS interrupts functions similarly to DHCP & SNTP, if releasing SNTP.
